### ISSUE TITLE
error in pagekit search

### ISSUE THREAD

**Issue by arceliver** [neicv/pagekit-search#1]
Hey neicv,

I have a OS X, with El Captain. I'm getting an error of array to string conversion... am I doing something wrong?

Thx

**Comment by neicv** [comment]
u try install 0.1.2 ver ?

**Comment by tux-86** [comment]
It seems that version 0.1.2 working well.

**Comment by neicv** [comment]
arceliver, Hi! Are u there?

**Comment by neicv** [comment]
Closed.
Reason - no reaction.
