### ISSUE TITLE
Link problem

### ISSUE THREAD

**Issue by yaelduckwen** [neicv/pagekit-search#10]
The url of the Search Results Dropdown (in widget) generate a bad link, the site folder is repeated

![image](https://cloud.githubusercontent.com/assets/16963836/25762341/ccf2d514-31b4-11e7-89f8-0e1f89931588.png)

**Comment by neicv** [comment]
Hi Yaelduckwen!
Server parameters? (PHP ver, OS, DB ver) ?

**Comment by yaelduckwen** [comment]
hi @neicv 

- localhost on xampp,
- pagekit 1.0.11
- Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.19
- windows 7

thanks you in advance

**Comment by neicv** [comment]
Hi!
Change:
..\packages\friendlyit\search\src\Controller\SiteController.php

line 351:
$item['url']   = App::url($res->href);
To:
$item['url']   = $res->href;

thanks !

**Comment by yaelduckwen** [comment]
Thanks man!
I'm working on a Spanish version of the plugin. I'll finish it soon.

**Comment by neicv** [comment]
Many thanks man!
Sound is good! And i'll glad to get your version! Very nice.
