### ISSUE TITLE
Search title can't be hidden - only reads as "Search Title"

### ISSUE THREAD

**Issue by humantex** [neicv/pagekit-search#13]
No settings choices will hide or change the title on the search/results page. Overriding the view by commenting out `<?= ($params['title'])?>` at line 5 in a theme's copy of placeholder.php - and then replacing it with a suitable text string was a quick but dirty solution.

Pagekit - v.1.0.13
Web Server - LiteSpeed
PHP - 5.6.32
DB - sqlite v.3.8.5
search ext. - v.0.1.6

**Comment by neicv** [comment]
Hi!
U use self modifed placeholder.php or default ?

**Comment by humantex** [comment]
I started with the default, but when I could not change the widget's title text with the built-in functions on the admin's settings page - I had no other choice and had to create my own placeholder.php file so I could alter the default code with a comment, and insert my own title in it's place.

Original file, with no override (search page title = "**Site Title**"):

```
<?php if($params['show_title']): ?>
	<h1 class="tm-article-subtitle">
		<?= ($params['title'])?>
	</h1>
<?php endif ?>
```

After the override - with a new placeholder.php file inside the theme's view folder (search page title = "**Site Search**"):

```
<?php if($params['show_title']): ?>
	<h1 class="tm-article-subtitle">
		<!--<?= ($params['title'])?>-->
		Site Search
	</h1>
<?php endif ?>
```
None of the settings marked with a red X in the attached screengrab crops can be modified...

![pagekit-search-issues](https://user-images.githubusercontent.com/16087649/32757716-d21f9d6a-c8ae-11e7-9b72-c87818f719bb.jpg)

**Comment by humantex** [comment]
Sorry... I **_can_** change the Menu Title, but the rest won't work.

**Comment by neicv** [comment]
hmm....need think...
ok.  override... I'll test it as soon as I can.

I will clarify just in case:
placeholder.php - this file can cystomize @search PAGE, not widgets.
"THEME" settings - its core settings. not my extension...

Additionally, the appearance can be customized using your theme.
Search extension, like Pagekit, use UIKIT. 
U can create self theme, add position - layout and other....
make theme.less include all u want to overide "uk-search" class.

my first oficial site: 
i-exist.ru
have self theme.
you can see what it looks like search page and search widgets.

**Comment by humantex** [comment]
Okay... I think I've found out where the change has to be made... at **my-site.com/admin/search/settings** and NOT on the widget or site's page listings. Sorry... I totally missed the link on the extensions listing page.
