### ISSUE TITLE
How to select language?

### ISSUE THREAD

**Issue by joseincandenza** [neicv/pagekit-search#16]
I see that you have some languages configured, mine among them, but I don't see any option to change language in the widget options. How can I do that?

**Comment by neicv** [comment]
Hi! Set Language widget and search page depends on settings: System->Localisation->Site Locale
Now have 4 opt language - rus, de, esp, eng
If you need add another language - create in "domain_name...\packages\friendlyit\search\languages\"
file and dir like exist in pakage.

**Comment by joseincandenza** [comment]
Hi neicv, thanks for your answer. The problem was that the installed version from pagekit marketplace doesn't include the es_ES language. I have created it in my installation and now everything works. Thank you very much for your assistance!
