### ISSUE TITLE
 Call to undefined function in SearchPagePlugin.php on line 111

### ISSUE THREAD

**Issue by claudericke** [neicv/pagekit-search#6]
I am getting the following error:

Fatal error: Call to undefined function Friendlyit\Search\Plugin\mysql_escape_string() in ...packages\friendlyit\search\src\Plugin\SearchPagePlugin.php on line 111

The error seems to be related to the allegedly depreciated mysql_escape_string(). Not that great with PHP so not entirely sure how to fix it myself. Waiting on your update. 

**System Information**

PHP Version 5.6.15
Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.15

**Comment by neicv** [comment]
Hi! Test plz 0.1.6 rel.
