### ISSUE TITLE
Extension incompatible with sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by BCool13** [neicv/pagekit-search#7]
Thank you for this useful extension.

Just one detail the queries are not compatible with MySql setting **sql_mode=only_full_group_by**.

The simplest fix seems to be:

In file  \src\plugin\searchblogplugin.php:

Change line 207 from : $query->groupBy('a.title', 'a.content', 'a.excerpt');
                               to : $query->groupBy('a.title', 'a.content', 'a.excerpt','a.id');
Change Line 311 from: $query->groupBy('post_id','content');
                                to: $query->groupBy('post_id','content','pk_blog_comment.id');

In file  \src\plugin\searchpageplugin.php:
Change Line 209  from: $query->groupBy('a.title, a.content');
			         to: $query->groupBy('a.title, a.content,a.id,c.id');

**Comment by kareensa** [comment]
Thanks for the help.
Very helpful.

**Comment by neicv** [comment]
Many Thanks!

**Comment by basttian** [comment]
solved it. thank U

**Comment by BCool13** [comment]
My pleasure.
