### ISSUE TITLE
API for other plugins

### ISSUE THREAD

**Issue by antonoff** [neicv/pagekit-search#8]
Hi! Thanks for your plugin! I think it will be so cool if there is an search API for other plugins.

**Comment by neicv** [comment]
Hi! I right understand -  did you mean to search for a data belonging to other extensions?
(Please give your contact. we discuss this outside GitHub)

**Comment by antonoff** [comment]
iamalexantonov (at) gmail.com

**Comment by justlovejazz** [comment]
Hello! I also want to know this. zzexel (at) gmail.com

**Comment by neicv** [comment]
Hi, just write WiKi Now. U can read this. I welcome the comments.

**Comment by justlovejazz** [comment]
Hello, and thank you! on the site there is an extension "Driveen Listings", which displays the content list-by-page, but Search does not display results from this list. Could you give some advice to solve this problem? I would be very grateful for the help in the decision. P.S. And is it possible to ignore the case when searching?

**Comment by neicv** [comment]
Hi! will try to help, but I  need some time to get to know this extension.
And I'm not sure what you understood correctly about P.S.

**Comment by justlovejazz** [comment]
Good afternoon. How are you? I meant to ignore upper and lower case letters when searching. and what about the expansion?

**Comment by neicv** [comment]
Hi!
1. Case ignores (tetsting on all my project and sites). You are the first, who mentioned this. MB its bugs.  Any add information?
2. "Driveen Listings" not simple extension. Need to think how to show the results and stuff ..etc...

**Comment by neicv** [comment]
1.  "Driveen Listings" extension added in 0.1.7.x ver.

2. "ignore upper and lower case letters when searching" - added and fixed in  0.1.7.7 ver.
